// src/routes/(legal)/legal/+page.svelte
<script>
	import Icon from '@iconify/svelte';

	const legalDocs = [
		{
			title: 'Terms of Service',
			description:
				'Our terms and conditions for using PowerIRL services. Includes information about user obligations, payment terms, and service availability.',
			path: '/legal/tos',
			icon: 'mdi:file-document'
		},
		{
			title: 'Privacy Policy',
			description:
				'Learn how we collect, use, and protect your personal information. Details about data security, retention, and your privacy rights.',
			path: '/legal/privacy',
			icon: 'mdi:shield-lock'
		},
		{
			title: 'Disclaimer',
			description:
				'Important information about service limitations, liability, and your responsibilities when using PowerIRL.',
			path: '/legal/disclaimer',
			icon: 'mdi:alert-circle'
		}
	];
</script>

<div class="container mx-auto px-5 py-8">
	<h1 class="mb-12 text-center text-3xl font-bold text-white sm:text-4xl">Legal Documents</h1>

	<div class="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
		{#each legalDocs as doc}
			<div
				class="group relative flex min-h-[320px] flex-col rounded-lg bg-[#121212]/80 p-8 text-center backdrop-blur-sm transition-all duration-500 hover:scale-105 hover:bg-[#121212] hover:shadow-lg sm:p-10"
			>
				<div
					class="absolute inset-0 rounded-lg bg-gradient-to-b from-white/5 to-transparent opacity-0 transition-opacity duration-300 group-hover:opacity-100"
				></div>
				<div class="flex-grow">
					<h2 class="mb-4 text-2xl font-bold text-white">{doc.title}</h2>
					<div class="mb-4 flex justify-center">
						<div class="flex h-16 w-16 items-center justify-center rounded-full bg-[#e20074]/10">
							<Icon icon={doc.icon} class="h-8 w-8 text-[#e20074]" />
						</div>
					</div>
					<p class="mb-8 text-base leading-relaxed text-gray-300">
						{doc.description}
					</p>
				</div>
				<div class="relative">
					<a
						href={doc.path}
						class="inline-block w-full cursor-pointer rounded-md bg-[#e20074] px-8 py-3 text-lg font-medium text-white transition-colors hover:bg-[#c70067] sm:px-12 sm:py-4"
					>
						Read
					</a>
				</div>
			</div>
		{/each}
	</div>
</div>

// src/app/(public)/legal/page.tsx
import Link from "next/link";
import { Icon } from "@iconify/react";

export default function LegalPage() {
  const legalDocs = [
    {
      title: "Terms of Service",
      description: "Our terms and conditions for using PowerIRL's services.",
      icon: "mdi:file-document-outline",
      href: "/legal/terms",
    },
    {
      title: "Privacy Policy",
      description: "How we collect, use, and protect your personal information.",
      icon: "mdi:shield-lock-outline",
      href: "/legal/privacy",
    },
    {
      title: "Disclaimer",
      description: "Important information about the use of our services.",
      icon: "mdi:alert-circle-outline",
      href: "/legal/disclaimer",
    },
  ];

  return (
    <div className="min-h-screen bg-[#18181b]">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-16">
        <div className="text-center mb-16">
          <h1 className="text-3xl md:text-5xl font-bold text-white mb-6 relative inline-block">
            <span className="relative z-10">Legal Information</span>
            <span className="absolute -bottom-2 left-0 w-full h-1 bg-[#E20074]"></span>
          </h1>
          <p className="text-center text-white max-w-3xl mx-auto text-lg">
            Important information about using PowerIRL's services. Please review
            these documents carefully.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {legalDocs.map((doc) => (
            <Link
              key={doc.title}
              href={doc.href}
              className="group flex flex-col items-center justify-center bg-black rounded-2xl shadow-lg hover:shadow-xl transition-all p-8 text-center focus:outline-none focus:ring-2 focus:ring-[#e20074]"
            >
              <div className="flex items-center justify-center mb-6">
                <span className="flex items-center justify-center w-20 h-20 rounded-full bg-[#e20074]/20">
                  <Icon icon={doc.icon} className="w-10 h-10 text-[#e20074]" />
                </span>
              </div>
              <h2 className="text-xl font-bold text-white mb-2">
                {doc.title}
              </h2>
              <p className="text-white opacity-80 mb-0">
                {doc.description}
              </p>
            </Link>
          ))}
        </div>

        <div className="mt-16 bg-black rounded-2xl shadow-lg p-8 flex flex-col items-center text-center">
          <h2 className="text-2xl font-semibold text-white mb-4">
            Need Help?
          </h2>
          <p className="text-white mb-6">
            If you have any questions about our legal documents or need
            clarification on any points, please join our Discord community.
          </p>
          <a
            href="https://discord.gg/powerirl"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 text-[#e20074] hover:text-[#ff00a0] font-medium transition-colors"
          >
            <Icon icon="mdi:discord" className="w-5 h-5" />
            Join Discord
          </a>
        </div>
      </div>
    </div>
  );
}
